name: "Liveblocks Dev Server"
description: "Start a Liveblocks dev server for integration testing"
branding:
  icon: "server"
  color: "purple"

inputs:
  port:
    description: "Port to expose the dev server on"
    required: false
    default: "1153"

outputs:
  url:
    description: "URL of the running dev server"
    value: http://localhost:${{ inputs.port }}

runs:
  using: "composite"
  steps:
    - uses: oven-sh/setup-bun@v2

    - name: Start dev server
      shell: bash
      run: |
        bunx liveblocks dev --host 0.0.0.0 --port ${{ inputs.port }} &

        for i in $(seq 1 30); do
          if curl -sf http://localhost:${{ inputs.port }}/health > /dev/null 2>&1; then
            echo "Liveblocks dev server is ready at http://localhost:${{ inputs.port }}"
            exit 0
          fi
          sleep 1
        done

        echo "::error::Liveblocks dev server failed to start within 30 seconds"
        exit 1
