name: "Liveblocks Dev Server"
description: "Start a Liveblocks dev server for integration testing"
branding:
  icon: "server"
  color: "purple"

inputs:
  port:
    description: "Port to expose the dev server on"
    required: false
    default: "1153"
  tag:
    description: "Docker image tag to use (e.g. 'latest', '1.0.5', 'pr-3060')"
    required: false
    default: "latest"

outputs:
  url:
    description: "URL of the running dev server"

runs:
  using: "docker"
  image: "docker://docker:cli"
  post-entrypoint: "cleanup.sh"
